// /**
//  * Database utilities module for interacting with the MySQL database.
//  *
//  * This module provides a collection of utility methods for performing
//  * common database operations such as Insert, Get, Update, Delete, and Query.
//  *
//  * It uses the mysql2/promise library for asynchronous database operations
//  * and supports dynamic schema manipulation through factory patterns.
//  *
//  * @module utilities/db-utilities
//  */

// import mysql, { ResultSetHeader } from "mysql2/promise";
// import { Factory } from "../../models/factory.model";
// import { Identifiable } from "../../models/identifiable.model";

// require("dotenv").config();

// /**
//  * TODO: Implement connection pooling for better performance and resource management.
//  * Currently, a new connection is created for each operation which can be inefficient
//  * under high load. Consider using mysql.createPool() and getConnection() from the pool.
//  */

// /**
//  * DbUtilities class provides database utility methods for performing CRUD operations.
//  *
//  * This class serves as a repository-style utility for interacting with the MySQL database.
//  * It uses dynamic SQL generation based on object properties and factory patterns
//  * to handle different entity types without requiring a separate repository class for each.
//  *
//  * @template T - The Identifiable entity type being operated on
//  * @example
//  * // Insert a new record
//  * await DbUtilities.Insert(newUser, UserFactory);
//  *
//  * @example
//  * // Get a record by ID
//  * const user = await DbUtilities.Get(userId, UserFactory);
//  *
//  * @example
//  * // Update a record
//  * await DbUtilities.Update(updatedUser, UserFactory);
//  *
//  * @example
//  * // Delete a record (hard delete)
//  * await DbUtilities.HardDelete(userId, UserFactory);
//  *
//  * @example
//  * // Query records with custom WHERE clause
//  * const users = await DbUtilities.Query("status = 'active'", UserFactory);
//  */
// export class DbUtilities {
//     /**
//      * Inserts a new record into the database.
//      *
//      * Dynamically constructs an INSERT SQL statement based on the properties
//      * of the provided object. Special handling is done for nested objects that
//      * implement the Factory interface, where only the ID is stored (foreign key reference).
//      *
//      * @template T - The Identifiable entity type
//      * @param o - The object to insert into the database. Must extend Identifiable.
//      * @param fac - Factory instance for the entity type, used to get collection name and Make method.
//      * @returns A ResultSetHeader containing the last insert ID and affected rows information.
//      * @example
//      * ```typescript
//      * const newUser: User = { ID: null, name: "John", age: 30 };
//      * const factory = UserFactory;
//      * await DbUtilities.Insert(newUser, factory);
//      * ```
//      */
//     static async Insert<T extends Identifiable>(
//         o: T,
//         fac: Factory<T>,
//     ): Promise<ResultSetHeader> {
//         // Establish database connection
//         let connection = await DbUtilities.getConnection();

//         // Construct dynamic INSERT SQL using placeholders for column names and values
//         let com = `INSERT INTO ${fac.CollectionName} ($$KEYS$$) VALUE ($$VALUES$$)`;

//         // Arrays to collect column names and values for the INSERT statement
//         const keys: string[] = [];
//         const values: string[] = [];

//         // Iterate over object properties and build the insert columns/values
//         for (let kv of Object.entries(o)) {
//             // Skip the ID field - it will be auto-generated by the database
//             if (kv[0] === "ID") continue;

//             // Check if value is a nested object with factory capabilities
//             if (
//                 typeof kv[1] === "object" &&
//                 typeof kv[1].ID === "number" &&
//                 typeof kv[1].GetFactory !== undefined
//             ) {
//                 // Store nested object's ID (foreign key reference)
//                 keys.push(kv[0]);
//                 values.push(kv[1].ID);
//             } else {
//                 // Store the value as a JSON string for proper serialization
//                 keys.push(kv[0]);
//                 values.push(JSON.stringify(kv[1]));
//             }
//         }

//         // Replace placeholders with actual column names and values
//         com = com
//             .replace("$$KEYS$$", keys.join(","))
//             .replace("$$VALUES$$", values.join(","));

//         // Execute the INSERT query
//         let [result, _] = await connection.query(com);

//         return result as ResultSetHeader;
//     }

//     /**
//      * Retrieves a single record from the database by its ID.
//      *
//      * Performs a SELECT query to fetch the record and uses the factory's Make method
//      * to reconstruct the object with proper typing. If no record is found, throws an error.
//      *
//      * @template T - The Identifiable entity type
//      * @param id - The ID of the record to retrieve
//      * @param factory - Factory instance for the entity type
//      * @returns The retrieved record as type T
//      * @throws Error if no record is found with the given ID
//      * @example
//      * ```typescript
//      * const user = await DbUtilities.Get(1, UserFactory);
//      * ```
//      */
//     static async Get<T extends Identifiable>(
//         id: number,
//         factory: Factory<T>,
//     ): Promise<T> {
//         // Establish database connection
//         let connection = await DbUtilities.getConnection();

//         // Execute SELECT query to fetch the record
//         const [result, _] = await connection.query(
//             `SELECT * FROM ${factory.CollectionName} WHERE ID = ?`,
//             [id],
//         );

//         // Reconstruct the array with proper types by removing circular references
//         const results: T[] = JSON.parse(JSON.stringify(result));

//         // Return the found record or throw error
//         if (results.length > 0) {
//             return factory.Make(results[0]);
//         } else {
//             throw new Error("No results found");
//         }
//     }

//     /**
//      * Updates an existing record in the database.
//      *
//      * Dynamically constructs an UPDATE SQL statement based on the properties
//      * of the provided object. Only specified fields are updated. The record
//      * must exist for the update to succeed, otherwise an error is thrown.
//      *
//      * @template T - The Identifiable entity type
//      * @param o - The object containing updated values
//      * @param factory - Factory instance for the entity type
//      * @returns The updated record as type T
//      * @throws Error if no record exists with the given ID
//      * @example
//      * ```typescript
//      * const updatedUser: User = { ID: 1, name: "John Doe", age: 31 };
//      * await DbUtilities.Update(updatedUser, UserFactory);
//      * ```
//      */
//     static async Update<T extends Identifiable>(o: T, factory: Factory<T>) {
//         // Establish database connection
//         let connection = await DbUtilities.getConnection();

//         // Build SET clause with field assignments
//         let fields = [];
//         for (let kv of Object.entries(o)) {
//             // Skip the ID field - use it for WHERE clause
//             if (kv[0] === "ID") continue;

//             // Check if value is a nested object with factory capabilities
//             if (
//                 typeof kv[1] === "object" &&
//                 typeof kv[1].ID === "number" &&
//                 typeof kv[1].GetFactory !== undefined
//             ) {
//                 // Store nested object's ID (foreign key reference)
//                 fields.push(`${kv[0]}=${kv[1].ID}`);
//             } else {
//                 // Store the value as a JSON string
//                 fields.push(`${kv[0]}=${JSON.stringify(kv[1])}`);
//             }
//         }

//         // Execute the UPDATE query (note: ID is not parameterized to get updated record)
//         const [result, _] = await connection.query(
//             `UPDATE ${factory.CollectionName} SET ${fields.join(",")} WHERE ID = ${o.ID} LIMIT 1`,
//         );

//         // Reconstruct the array with proper types
//         const results: T[] = JSON.parse(JSON.stringify(result));

//         // Return the updated record or throw error
//         if (results.length > 0) {
//             return factory.Make(results[0]);
//         } else {
//             throw new Error("No results found");
//         }
//     }

//     /**
//      * Permanently deletes a record from the database (hard delete).
//      *
//      * WARNING: This method permanently removes the record from the database.
//      * Consider using soft delete by adding an isDeleted flag instead.
//      *
//      * @template T - The Identifiable entity type
//      * @param id - The ID of the record to delete
//      * @param factory - Factory instance for the entity type
//      * @example
//      * ```typescript
//      * await DbUtilities.HardDelete(1, UserFactory);
//      * ```
//      */
//     // NOTE: We rarely need to hard-delete objects. You should probably consider soft-deleting.
//     static async HardDelete<T extends Identifiable>(
//         id: string,
//         factory: Factory<T>,
//     ) {
//         // Establish database connection
//         let connection = await DbUtilities.getConnection();

//         // Execute DELETE query
//         await connection.query(
//             `DELETE FROM ${factory.CollectionName} WHERE ID = ? LIMIT 1`,
//             [id],
//         );

//         return;
//     }

//     /**
//      * Queries records from the database with optional pagination and projection.
//      *
//      * Performs a SELECT query with dynamic WHERE clause. Supports pagination
//      * through page and limit parameters. Returns mapped results using the factory.
//      * If no records are found, throws an error.
//      *
//      * @template T - The Identifiable entity type
//      * @param query - Dynamic WHERE clause (e.g., "status = 'active'")
//      * @param factory - Factory instance for the entity type
//      * @param projection - Array of columns to select (default: all columns)
//      * @param limit - Maximum number of records per page
//      * @param page - Page number for pagination (0-indexed)
//      * @returns Array of records as type T
//      * @throws Error if no records are found
//      * @example
//      * ```typescript
//      * const users = await DbUtilities.Query(
//      *   "status = 'active'",
//      *   UserFactory,
//      *   ["*"],
//      *   10,
//      *   0
//      * );
//      * ```
//      */
//     static async Query<T>(
//         query: any,
//         factory: Factory<T>,
//         projection: string[] = ["*"],
//         limit: number = parseInt(process.env.DEFAULT_QUERY_LIMIT),
//         page: number = 0,
//     ): Promise<T[]> {
//         // Establish database connection
//         const connection = await DbUtilities.getConnection();

//         let sql = `SELECT ${projection.join(",")} FROM ${factory.CollectionName} WHERE ${query} LIMIT ${page * limit},${limit}`;

//         console.log(sql);

//         // Execute SELECT query with pagination
//         const [result, _] = await connection.query(sql);

//         // Reconstruct the array with proper types
//         const results: T[] = JSON.parse(JSON.stringify(result));

//         // Return mapped results or throw error if no records found
//         if (results.length > 0) {
//             return results.map((r) => factory.Make(r));
//         } else {
//             throw new Error("No results found");
//         }
//     }

//     /**
//      * Creates and returns a MySQL database connection.
//      *
//      * This private method establishes a new connection to the MySQL database
//      * using environment variables for connection configuration.
//      *
//      * Required environment variables:
//      * - DB_HOST: Database host address
//      * - DB_USER: Database username
//      * - DB_PASS: Database password
//      * - DB_NAME: Database name
//      *
//      * @returns A Promise that resolves to a mysql connection object
//      * @private
//      */
//     private static async getConnection() {
//         return await mysql.createConnection({
//             host: process.env.DB_HOST,
//             user: process.env.DB_USER,
//             password: process.env.DB_PASS,
//             database: process.env.DB_NAME,
//         });
//     }
// }
